from django.forms import ModelForm
from .models import Itinerary

#setting up our autogenerated form for feeding

#extending/inheritin ModelForm to have all it Django Functionalities 
class ItineraryForm(ModelForm):
    class Meta:
        model = Itinerary
        #and what fields of model to show
        fields = ["date", "notes"]