# Generated by Django 4.1.1 on 2022-10-31 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_itinerary_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-date']},
        ),
    ]
